// HPS.v

// Generated using ACDS version 25.1 1129

`timescale 1 ps / 1 ps
module HPS (
		input  wire         hps_0_f2h_sdram0_clock_clk,    // hps_0_f2h_sdram0_clock.clk
		input  wire [31:0]  hps_0_f2h_sdram0_data_araddr,  //  hps_0_f2h_sdram0_data.araddr
		input  wire [3:0]   hps_0_f2h_sdram0_data_arlen,   //                       .arlen
		input  wire [7:0]   hps_0_f2h_sdram0_data_arid,    //                       .arid
		input  wire [2:0]   hps_0_f2h_sdram0_data_arsize,  //                       .arsize
		input  wire [1:0]   hps_0_f2h_sdram0_data_arburst, //                       .arburst
		input  wire [1:0]   hps_0_f2h_sdram0_data_arlock,  //                       .arlock
		input  wire [2:0]   hps_0_f2h_sdram0_data_arprot,  //                       .arprot
		input  wire         hps_0_f2h_sdram0_data_arvalid, //                       .arvalid
		input  wire [3:0]   hps_0_f2h_sdram0_data_arcache, //                       .arcache
		input  wire [31:0]  hps_0_f2h_sdram0_data_awaddr,  //                       .awaddr
		input  wire [3:0]   hps_0_f2h_sdram0_data_awlen,   //                       .awlen
		input  wire [7:0]   hps_0_f2h_sdram0_data_awid,    //                       .awid
		input  wire [2:0]   hps_0_f2h_sdram0_data_awsize,  //                       .awsize
		input  wire [1:0]   hps_0_f2h_sdram0_data_awburst, //                       .awburst
		input  wire [1:0]   hps_0_f2h_sdram0_data_awlock,  //                       .awlock
		input  wire [2:0]   hps_0_f2h_sdram0_data_awprot,  //                       .awprot
		input  wire         hps_0_f2h_sdram0_data_awvalid, //                       .awvalid
		input  wire [3:0]   hps_0_f2h_sdram0_data_awcache, //                       .awcache
		output wire [1:0]   hps_0_f2h_sdram0_data_bresp,   //                       .bresp
		output wire [7:0]   hps_0_f2h_sdram0_data_bid,     //                       .bid
		output wire         hps_0_f2h_sdram0_data_bvalid,  //                       .bvalid
		input  wire         hps_0_f2h_sdram0_data_bready,  //                       .bready
		output wire         hps_0_f2h_sdram0_data_arready, //                       .arready
		output wire         hps_0_f2h_sdram0_data_awready, //                       .awready
		input  wire         hps_0_f2h_sdram0_data_rready,  //                       .rready
		output wire [127:0] hps_0_f2h_sdram0_data_rdata,   //                       .rdata
		output wire [1:0]   hps_0_f2h_sdram0_data_rresp,   //                       .rresp
		output wire         hps_0_f2h_sdram0_data_rlast,   //                       .rlast
		output wire [7:0]   hps_0_f2h_sdram0_data_rid,     //                       .rid
		output wire         hps_0_f2h_sdram0_data_rvalid,  //                       .rvalid
		input  wire         hps_0_f2h_sdram0_data_wlast,   //                       .wlast
		input  wire         hps_0_f2h_sdram0_data_wvalid,  //                       .wvalid
		input  wire [127:0] hps_0_f2h_sdram0_data_wdata,   //                       .wdata
		input  wire [15:0]  hps_0_f2h_sdram0_data_wstrb,   //                       .wstrb
		output wire         hps_0_f2h_sdram0_data_wready,  //                       .wready
		input  wire [7:0]   hps_0_f2h_sdram0_data_wid,     //                       .wid
		output wire         hps_0_h2f_reset_reset_n,       //        hps_0_h2f_reset.reset_n
		output wire [12:0]  memory_mem_a,                  //                 memory.mem_a
		output wire [2:0]   memory_mem_ba,                 //                       .mem_ba
		output wire         memory_mem_ck,                 //                       .mem_ck
		output wire         memory_mem_ck_n,               //                       .mem_ck_n
		output wire         memory_mem_cke,                //                       .mem_cke
		output wire         memory_mem_cs_n,               //                       .mem_cs_n
		output wire         memory_mem_ras_n,              //                       .mem_ras_n
		output wire         memory_mem_cas_n,              //                       .mem_cas_n
		output wire         memory_mem_we_n,               //                       .mem_we_n
		output wire         memory_mem_reset_n,            //                       .mem_reset_n
		inout  wire [7:0]   memory_mem_dq,                 //                       .mem_dq
		inout  wire         memory_mem_dqs,                //                       .mem_dqs
		inout  wire         memory_mem_dqs_n,              //                       .mem_dqs_n
		output wire         memory_mem_odt,                //                       .mem_odt
		output wire         memory_mem_dm,                 //                       .mem_dm
		input  wire         memory_oct_rzqin               //                       .oct_rzqin
	);

	HPS_hps_0 #(
		.F2S_Width (0),
		.S2F_Width (0)
	) hps_0 (
		.mem_a              (memory_mem_a),                  //           memory.mem_a
		.mem_ba             (memory_mem_ba),                 //                 .mem_ba
		.mem_ck             (memory_mem_ck),                 //                 .mem_ck
		.mem_ck_n           (memory_mem_ck_n),               //                 .mem_ck_n
		.mem_cke            (memory_mem_cke),                //                 .mem_cke
		.mem_cs_n           (memory_mem_cs_n),               //                 .mem_cs_n
		.mem_ras_n          (memory_mem_ras_n),              //                 .mem_ras_n
		.mem_cas_n          (memory_mem_cas_n),              //                 .mem_cas_n
		.mem_we_n           (memory_mem_we_n),               //                 .mem_we_n
		.mem_reset_n        (memory_mem_reset_n),            //                 .mem_reset_n
		.mem_dq             (memory_mem_dq),                 //                 .mem_dq
		.mem_dqs            (memory_mem_dqs),                //                 .mem_dqs
		.mem_dqs_n          (memory_mem_dqs_n),              //                 .mem_dqs_n
		.mem_odt            (memory_mem_odt),                //                 .mem_odt
		.mem_dm             (memory_mem_dm),                 //                 .mem_dm
		.oct_rzqin          (memory_oct_rzqin),              //                 .oct_rzqin
		.h2f_rst_n          (hps_0_h2f_reset_reset_n),       //        h2f_reset.reset_n
		.f2h_sdram0_clk     (hps_0_f2h_sdram0_clock_clk),    // f2h_sdram0_clock.clk
		.f2h_sdram0_ARADDR  (hps_0_f2h_sdram0_data_araddr),  //  f2h_sdram0_data.araddr
		.f2h_sdram0_ARLEN   (hps_0_f2h_sdram0_data_arlen),   //                 .arlen
		.f2h_sdram0_ARID    (hps_0_f2h_sdram0_data_arid),    //                 .arid
		.f2h_sdram0_ARSIZE  (hps_0_f2h_sdram0_data_arsize),  //                 .arsize
		.f2h_sdram0_ARBURST (hps_0_f2h_sdram0_data_arburst), //                 .arburst
		.f2h_sdram0_ARLOCK  (hps_0_f2h_sdram0_data_arlock),  //                 .arlock
		.f2h_sdram0_ARPROT  (hps_0_f2h_sdram0_data_arprot),  //                 .arprot
		.f2h_sdram0_ARVALID (hps_0_f2h_sdram0_data_arvalid), //                 .arvalid
		.f2h_sdram0_ARCACHE (hps_0_f2h_sdram0_data_arcache), //                 .arcache
		.f2h_sdram0_AWADDR  (hps_0_f2h_sdram0_data_awaddr),  //                 .awaddr
		.f2h_sdram0_AWLEN   (hps_0_f2h_sdram0_data_awlen),   //                 .awlen
		.f2h_sdram0_AWID    (hps_0_f2h_sdram0_data_awid),    //                 .awid
		.f2h_sdram0_AWSIZE  (hps_0_f2h_sdram0_data_awsize),  //                 .awsize
		.f2h_sdram0_AWBURST (hps_0_f2h_sdram0_data_awburst), //                 .awburst
		.f2h_sdram0_AWLOCK  (hps_0_f2h_sdram0_data_awlock),  //                 .awlock
		.f2h_sdram0_AWPROT  (hps_0_f2h_sdram0_data_awprot),  //                 .awprot
		.f2h_sdram0_AWVALID (hps_0_f2h_sdram0_data_awvalid), //                 .awvalid
		.f2h_sdram0_AWCACHE (hps_0_f2h_sdram0_data_awcache), //                 .awcache
		.f2h_sdram0_BRESP   (hps_0_f2h_sdram0_data_bresp),   //                 .bresp
		.f2h_sdram0_BID     (hps_0_f2h_sdram0_data_bid),     //                 .bid
		.f2h_sdram0_BVALID  (hps_0_f2h_sdram0_data_bvalid),  //                 .bvalid
		.f2h_sdram0_BREADY  (hps_0_f2h_sdram0_data_bready),  //                 .bready
		.f2h_sdram0_ARREADY (hps_0_f2h_sdram0_data_arready), //                 .arready
		.f2h_sdram0_AWREADY (hps_0_f2h_sdram0_data_awready), //                 .awready
		.f2h_sdram0_RREADY  (hps_0_f2h_sdram0_data_rready),  //                 .rready
		.f2h_sdram0_RDATA   (hps_0_f2h_sdram0_data_rdata),   //                 .rdata
		.f2h_sdram0_RRESP   (hps_0_f2h_sdram0_data_rresp),   //                 .rresp
		.f2h_sdram0_RLAST   (hps_0_f2h_sdram0_data_rlast),   //                 .rlast
		.f2h_sdram0_RID     (hps_0_f2h_sdram0_data_rid),     //                 .rid
		.f2h_sdram0_RVALID  (hps_0_f2h_sdram0_data_rvalid),  //                 .rvalid
		.f2h_sdram0_WLAST   (hps_0_f2h_sdram0_data_wlast),   //                 .wlast
		.f2h_sdram0_WVALID  (hps_0_f2h_sdram0_data_wvalid),  //                 .wvalid
		.f2h_sdram0_WDATA   (hps_0_f2h_sdram0_data_wdata),   //                 .wdata
		.f2h_sdram0_WSTRB   (hps_0_f2h_sdram0_data_wstrb),   //                 .wstrb
		.f2h_sdram0_WREADY  (hps_0_f2h_sdram0_data_wready),  //                 .wready
		.f2h_sdram0_WID     (hps_0_f2h_sdram0_data_wid)      //                 .wid
	);

endmodule
