// Copyright (C) 2025  Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Altera and sold by Altera or its authorized distributors.  Please
// refer to the Altera Software License Subscription Agreements 
// on the Quartus Prime software download page.


// Generated by Quartus Prime Version 25.1 (Build Build 1129 10/21/2025)
// Created on Sun Mar 29 23:39:01 2026

register_bank register_bank_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.n_rst(n_rst_sig) ,	// input  n_rst_sig
	.rs1(rs1_sig) ,	// input [(ADD_BUS_WIDTH-1):0] rs1_sig
	.rs2(rs2_sig) ,	// input [(ADD_BUS_WIDTH-1):0] rs2_sig
	.rs1data(rs1data_sig) ,	// output [(WSIZE-1):0] rs1data_sig
	.rs2data(rs2data_sig) ,	// output [(WSIZE-1):0] rs2data_sig
	.rd(rd_sig) ,	// input [(ADD_BUS_WIDTH-1):0] rd_sig
	.rddata(rddata_sig) ,	// input [(WSIZE-1):0] rddata_sig
	.mem_data(mem_data_sig) ,	// inout [(WSIZE-1):0] mem_data_sig
	.mem_write(mem_write_sig) ,	// output  mem_write_sig
	.mem_ready(mem_ready_sig) ,	// input  mem_ready_sig
	.mem_read_out(mem_read_out_sig) ,	// output [(WSIZE-1):0] mem_read_out_sig
	.imm(imm_sig) ,	// input [(WSIZE-1):0] imm_sig
	.inst_write_mem(inst_write_mem_sig) ,	// input  inst_write_mem_sig
	.inst_read_mem(inst_read_mem_sig) ,	// input  inst_read_mem_sig
	.inst_write_rd(inst_write_rd_sig) 	// input  inst_write_rd_sig
);

defparam register_bank_inst.NUM_REGISTERS = 32;
defparam register_bank_inst.WSIZE = 32;
//defparam register_bank_inst.ADD_BUS_WIDTH = ;
