	HPS u0 (
		.hps_0_f2h_sdram0_clock_clk    (<connected-to-hps_0_f2h_sdram0_clock_clk>),    // hps_0_f2h_sdram0_clock.clk
		.hps_0_f2h_sdram0_data_araddr  (<connected-to-hps_0_f2h_sdram0_data_araddr>),  //  hps_0_f2h_sdram0_data.araddr
		.hps_0_f2h_sdram0_data_arlen   (<connected-to-hps_0_f2h_sdram0_data_arlen>),   //                       .arlen
		.hps_0_f2h_sdram0_data_arid    (<connected-to-hps_0_f2h_sdram0_data_arid>),    //                       .arid
		.hps_0_f2h_sdram0_data_arsize  (<connected-to-hps_0_f2h_sdram0_data_arsize>),  //                       .arsize
		.hps_0_f2h_sdram0_data_arburst (<connected-to-hps_0_f2h_sdram0_data_arburst>), //                       .arburst
		.hps_0_f2h_sdram0_data_arlock  (<connected-to-hps_0_f2h_sdram0_data_arlock>),  //                       .arlock
		.hps_0_f2h_sdram0_data_arprot  (<connected-to-hps_0_f2h_sdram0_data_arprot>),  //                       .arprot
		.hps_0_f2h_sdram0_data_arvalid (<connected-to-hps_0_f2h_sdram0_data_arvalid>), //                       .arvalid
		.hps_0_f2h_sdram0_data_arcache (<connected-to-hps_0_f2h_sdram0_data_arcache>), //                       .arcache
		.hps_0_f2h_sdram0_data_awaddr  (<connected-to-hps_0_f2h_sdram0_data_awaddr>),  //                       .awaddr
		.hps_0_f2h_sdram0_data_awlen   (<connected-to-hps_0_f2h_sdram0_data_awlen>),   //                       .awlen
		.hps_0_f2h_sdram0_data_awid    (<connected-to-hps_0_f2h_sdram0_data_awid>),    //                       .awid
		.hps_0_f2h_sdram0_data_awsize  (<connected-to-hps_0_f2h_sdram0_data_awsize>),  //                       .awsize
		.hps_0_f2h_sdram0_data_awburst (<connected-to-hps_0_f2h_sdram0_data_awburst>), //                       .awburst
		.hps_0_f2h_sdram0_data_awlock  (<connected-to-hps_0_f2h_sdram0_data_awlock>),  //                       .awlock
		.hps_0_f2h_sdram0_data_awprot  (<connected-to-hps_0_f2h_sdram0_data_awprot>),  //                       .awprot
		.hps_0_f2h_sdram0_data_awvalid (<connected-to-hps_0_f2h_sdram0_data_awvalid>), //                       .awvalid
		.hps_0_f2h_sdram0_data_awcache (<connected-to-hps_0_f2h_sdram0_data_awcache>), //                       .awcache
		.hps_0_f2h_sdram0_data_bresp   (<connected-to-hps_0_f2h_sdram0_data_bresp>),   //                       .bresp
		.hps_0_f2h_sdram0_data_bid     (<connected-to-hps_0_f2h_sdram0_data_bid>),     //                       .bid
		.hps_0_f2h_sdram0_data_bvalid  (<connected-to-hps_0_f2h_sdram0_data_bvalid>),  //                       .bvalid
		.hps_0_f2h_sdram0_data_bready  (<connected-to-hps_0_f2h_sdram0_data_bready>),  //                       .bready
		.hps_0_f2h_sdram0_data_arready (<connected-to-hps_0_f2h_sdram0_data_arready>), //                       .arready
		.hps_0_f2h_sdram0_data_awready (<connected-to-hps_0_f2h_sdram0_data_awready>), //                       .awready
		.hps_0_f2h_sdram0_data_rready  (<connected-to-hps_0_f2h_sdram0_data_rready>),  //                       .rready
		.hps_0_f2h_sdram0_data_rdata   (<connected-to-hps_0_f2h_sdram0_data_rdata>),   //                       .rdata
		.hps_0_f2h_sdram0_data_rresp   (<connected-to-hps_0_f2h_sdram0_data_rresp>),   //                       .rresp
		.hps_0_f2h_sdram0_data_rlast   (<connected-to-hps_0_f2h_sdram0_data_rlast>),   //                       .rlast
		.hps_0_f2h_sdram0_data_rid     (<connected-to-hps_0_f2h_sdram0_data_rid>),     //                       .rid
		.hps_0_f2h_sdram0_data_rvalid  (<connected-to-hps_0_f2h_sdram0_data_rvalid>),  //                       .rvalid
		.hps_0_f2h_sdram0_data_wlast   (<connected-to-hps_0_f2h_sdram0_data_wlast>),   //                       .wlast
		.hps_0_f2h_sdram0_data_wvalid  (<connected-to-hps_0_f2h_sdram0_data_wvalid>),  //                       .wvalid
		.hps_0_f2h_sdram0_data_wdata   (<connected-to-hps_0_f2h_sdram0_data_wdata>),   //                       .wdata
		.hps_0_f2h_sdram0_data_wstrb   (<connected-to-hps_0_f2h_sdram0_data_wstrb>),   //                       .wstrb
		.hps_0_f2h_sdram0_data_wready  (<connected-to-hps_0_f2h_sdram0_data_wready>),  //                       .wready
		.hps_0_f2h_sdram0_data_wid     (<connected-to-hps_0_f2h_sdram0_data_wid>),     //                       .wid
		.hps_0_h2f_reset_reset_n       (<connected-to-hps_0_h2f_reset_reset_n>),       //        hps_0_h2f_reset.reset_n
		.memory_mem_a                  (<connected-to-memory_mem_a>),                  //                 memory.mem_a
		.memory_mem_ba                 (<connected-to-memory_mem_ba>),                 //                       .mem_ba
		.memory_mem_ck                 (<connected-to-memory_mem_ck>),                 //                       .mem_ck
		.memory_mem_ck_n               (<connected-to-memory_mem_ck_n>),               //                       .mem_ck_n
		.memory_mem_cke                (<connected-to-memory_mem_cke>),                //                       .mem_cke
		.memory_mem_cs_n               (<connected-to-memory_mem_cs_n>),               //                       .mem_cs_n
		.memory_mem_ras_n              (<connected-to-memory_mem_ras_n>),              //                       .mem_ras_n
		.memory_mem_cas_n              (<connected-to-memory_mem_cas_n>),              //                       .mem_cas_n
		.memory_mem_we_n               (<connected-to-memory_mem_we_n>),               //                       .mem_we_n
		.memory_mem_reset_n            (<connected-to-memory_mem_reset_n>),            //                       .mem_reset_n
		.memory_mem_dq                 (<connected-to-memory_mem_dq>),                 //                       .mem_dq
		.memory_mem_dqs                (<connected-to-memory_mem_dqs>),                //                       .mem_dqs
		.memory_mem_dqs_n              (<connected-to-memory_mem_dqs_n>),              //                       .mem_dqs_n
		.memory_mem_odt                (<connected-to-memory_mem_odt>),                //                       .mem_odt
		.memory_mem_dm                 (<connected-to-memory_mem_dm>),                 //                       .mem_dm
		.memory_oct_rzqin              (<connected-to-memory_oct_rzqin>)               //                       .oct_rzqin
	);

